Added some validation to handle bad URLs
projectdiscovery/katana pull request #1090
Opened 2024-11-04 19:51 UTC by SecGus

Added some validation to help deal with bad/wrong input URLs (which was causing segmentation faults & crashes).

2024-11-05 09:53 UTC, GeorginaReeder commented
Thanks for your contribution @SecGus , we appreciate it!

We also have a [Discord server](https://discord.com/invite/projectdiscovery), which you’re more than welcome to join. It's a great place to connect with fellow contributors and stay updated with the latest developments!

2024-11-06 08:32 UTC, dogancanbakir requested changes
Left some comments for you. Thanks for the PR!

2024-11-06 08:32 UTC, dogancanbakir commented on internal/runner/executer.go
> +		if input == "" {
This check can be done at https://github.com/projectdiscovery/katana/blob/main/internal/runner/options.go#L89

2024-11-06 08:32 UTC, dogancanbakir commented on internal/runner/executer.go
> +		if r.crawler == nil {
We can guard against at the beginning of this function. That way, nothing is done if crawler is nil.

2024-11-07 15:40 UTC, dogancanbakir approved these changes

2024-11-08 15:18 UTC, Mzack9999 approved these changes

2024-11-08 15:19 UTC, merged