Crawl the source map files
projectdiscovery/katana pull request #413
Opened 2023-04-20 09:39 UTC by ShubhamRasal

2023-04-20 18:32 UTC, Mzack9999 approved these changes
lgtm! - Question: By unmarshaling the json, we might detect more decoded endpoints, as many characters are escaped in the marshaled json and might not match the regexes?

2023-04-21 11:50 UTC, tarunKoyalwar reviewed
lgtm !

suggesting minor changes

2023-04-21 11:50 UTC, tarunKoyalwar commented on pkg/engine/parser/parser.go
> +					}
@ShubhamRasal , suggesting index checking to avoid `index out of bound panic`.

2023-04-21 11:50 UTC, tarunKoyalwar commented on pkg/engine/parser/parser.go
> +	}
@ShubhamRasal , not sure if there is a need to remove any existing parameters . we can clone any url struct using 
```go
	temp := urlutil.URL{URL: resp.Resp.Request.URL}
	cloned := temp.Clone()
```
and we can add to cloned.Path directly

2023-04-21 11:50 UTC, tarunKoyalwar commented on pkg/types/sourcemap.go
> +type SoruceMap struct {
typo `SourceMap`

2023-04-21 11:57 UTC, tarunKoyalwar commented
@Mzack9999 , a sample sourcemap file is available at below url 
```console
curl https://wac-cdn.atlassian.com/static/master/4466/assets/build/js/chunks/9b24561751aa1c.js.map | jq .
```
as you can tell running Endpoint regex and other regex on sourcemap content already generates lot of false positives this is due to 
- `filePaths` like `./utils` are considered as relative endpoints
- `third party` node_modules
- `mappings` & variable names might be considered as endpoint by regex

by unmarshalling and removing `node_modules` we are actually trying to reduce false positives .

ideal solution would be to also add a new regex since it is quite rare to find a url like `https://somethig.com/../abc` but we will definitely see relative js/ts import statements like `import ./utils`

2023-04-22 14:11 UTC, ehsandeep reviewed
```console
./katana -u https://wac-cdn.atlassian.com/static/master/4466/assets/build/js/chunks/9b24561751aa1c.js.map -jc -ns

   __        __                
  / /_____ _/ /____ ____  ___ _
 /  '_/ _  / __/ _  / _ \/ _  /
/_/\_\\_,_/\__/\_,_/_//_/\_,_/							 

		projectdiscovery.io

[INF] Current katana version v1.0.2-dev (dev)
[INF] Started standard crawling for => https://wac-cdn.atlassian.com/static/master/4466/assets/build/js/chunks/9b24561751aa1c.js.map
https://wac-cdn.atlassian.com/static/master/4466/assets/build/js/chunks/9b24561751aa1c.js.map
```

2023-04-25 07:46 UTC, ShubhamRasal commented
![image](https://user-images.githubusercontent.com/45902122/234209158-b4232791-966c-4194-a135-f5e934d7cb19.png)

2023-04-25 12:05 UTC, ehsandeep approved these changes

2023-11-20 12:56 UTC, ehsandeep requested changes
```console
./katana -u https://bitbucket.org -jc -ns -v -proxy http://127.0.0.1:8080

   __        __                
  / /_____ _/ /____ ____  ___ _
 /  '_/ _  / __/ _  / _ \/ _  /
/_/\_\\_,_/\__/\_,_/_//_/\_,_/							 

		projectdiscovery.io

[INF] Current katana version v1.0.4 (latest)
[INF] Started standard crawling for => https://bitbucket.org
[GET] https://bitbucket.org
[html] [GET] http://www.w3.org/2000/svg
[script] [GET] https://atl-global.atlassian.com/js/atl-global.min.js
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10390b1fc]

goroutine 31 [running]:
github.com/projectdiscovery/utils/url.(*OrderedParams).Clone(0x0)
	/Users/geekboy/go/pkg/mod/github.com/projectdiscovery/utils@v0.0.60/url/orderedparams.go:157 +0x6c
github.com/projectdiscovery/utils/url.(*URL).Clone(0x1400128fd50)
	/Users/geekboy/go/pkg/mod/github.com/projectdiscovery/utils@v0.0.60/url/url.go:90 +0x204
github.com/projectdiscovery/katana/pkg/engine/parser.scriptJSFileRegexParser(0x140012a2790)
	/Users/geekboy/Github/katana/pkg/engine/parser/parser.go:674 +0x29c
github.com/projectdiscovery/katana/pkg/engine/parser.ParseResponse(0x140012a2790)
	/Users/geekboy/Github/katana/pkg/engine/parser/parser.go:101 +0x244
github.com/projectdiscovery/katana/pkg/engine/common.(*Shared).Do.func1()
	/Users/geekboy/Github/katana/pkg/engine/common/base.go:246 +0x174
created by github.com/projectdiscovery/katana/pkg/engine/common.(*Shared).Do in goroutine 61
	/Users/geekboy/Github/katana/pkg/engine/common/base.go:214 +0x250
```

2024-03-17 10:10 UTC, dogancanbakir commented
Closing this due to lost context. We'll review the issue again.

2024-03-17 10:10 UTC, closed without merging