Adds option to parse form, input, textarea & select elements
projectdiscovery/katana pull request #464
Opened 2023-06-05 08:54 UTC by aristosMiliaressis

Added the following option to parse forms
```
   -fx, -form-extraction        enable extraction of form, input, textarea & select elements
```

output format
```json
forms": [                                                                                                                                                                                                       
  {                                                                                                                                                                                                              
    "method": "POST",                                                                                                                                                                                            
    "action": "/test",                                                                                                                                                                                           
    "parameters": [                                                                                                                                                                                              
      "firstname",                                                                                                                                                                                               
      "textarea1",                                                                                                                                                                                               
      "select1"                                                                                                                                                                                                  
    ]                                                                                                                                                                                                            
  }                                                                                                                                                                                                              
]
```

2023-06-12 23:20 UTC, ehsandeep requested changes
@aristosMiliaressis looks very useful.

we can keep the inconsistent request method in the output uniform following CAPS for the method.

Current:

```json
cat output | jq '.response.forms[].method' | sort -u

"GET"
"POST"
"get"
"post"
``` 

Expected:

```json
cat output | jq '.response.forms[].method' | sort -u

"GET"
"POST"
```

2023-06-13 11:43 UTC, aristosMiliaressis commented
Hi @ehsandeep , thanks for the quick response, i just committed the change you suggested

2023-06-13 13:48 UTC, tarunKoyalwar approved these changes
lgtm !

@aristosMiliaressis thanks for PR and adding this awesome feature

```console
$ ./katana -u https://www.hackerone.com/contact -fx -j  -or -ob | jq '.response.forms | select( . != null )'

   __        __                
  / /_____ _/ /____ ____  ___ _
 /  '_/ _  / __/ _  / _ \/ _  /
/_/\_\\_,_/\__/\_,_/_//_/\_,_/							 

		projectdiscovery.io

[INF] Current katana version v1.0.2-dev (outdated)
[INF] Started standard crawling for => https://www.hackerone.com/contact
[
  {
    "method": "POST",
    "action": "/product/insights",
    "parameters": [
      "email",
      "op",
      "form_build_id",
      "form_id",
      "url"
    ]
  }
]
[
  {
    "method": "POST",
    "action": "/ethical-hacker",
    "parameters": [
      "email",
      "op",
      "form_build_id",
      "form_id",
      "url"
    ]
  }
]

```

2023-06-13 22:01 UTC, ehsandeep approved these changes

2023-06-13 22:04 UTC, merged