add `-store-field-dir` flag to store per-host field to custom directory
projectdiscovery/katana pull request #877
Opened 2024-05-06 06:39 UTC by dogancanbakir

Closes #874

2024-05-06 07:51 UTC, exploit-io commented
Thank You

2024-05-08 08:01 UTC, Mzack9999 approved these changes
lgtm - Unrelated to this PR, just noticing that the output files contain a lot of redundant data (especially the dir one). Shall we create a follow up issue to dedupe them once the scan is completed?

2024-06-27 08:14 UTC, ehsandeep requested changes
merge conflict

2024-06-27 09:16 UTC, ehsandeep approved these changes

2024-06-27 09:16 UTC, merged