Remove passive crawling
projectdiscovery/katana pull request #899
Opened 2024-05-20 20:41 UTC by dogancanbakir

Closes #898. Also #892 and [#5140](https://github.com/projectdiscovery/nuclei/issues/5140)

2024-05-22 16:57 UTC, zy9ard3 commented
Hey @dogancanbakir 

May I know why this feature is being removed after the bug ???

Thanks & Regards,
@zy9ard3

2024-05-22 19:17 UTC, zy9ard3 commented
@ehsandeep 

Thanks for the Acknowledgements !!

Yes, You're right !!

and that's a great news !! I'm eagerly waiting to see the new project for it

Have a Great Day : )

Thanks & Regards,
@zy9ard3

2024-06-27 09:37 UTC, ehsandeep requested changes
merge conflict

2024-08-07 14:10 UTC, Mzack9999 approved these changes

2024-08-08 09:29 UTC, merged