Update main.go
projectdiscovery/katana pull request #914
Opened 2024-06-03 14:08 UTC by geeknik

1. Error Handling: Centralized error handling with the handleError function to reduce code repetition.
2. Function Decomposition: Split the main function and readFlags function into smaller functions for better readability and maintainability.
3. Comments: Added comments to describe the purpose of functions and key sections of the code.
4. Concurrency Handling: Improved handling of signals for a graceful shutdown.

2024-06-03 15:51 UTC, GeorginaReeder commented
Great, thanks so much for your contribution @geeknik !

2024-11-29 12:02 UTC, dogancanbakir requested changes

2024-11-29 12:02 UTC, dogancanbakir commented on cmd/katana/main.go
> -	//use options.StoreFieldDir once https://github.com/projectdiscovery/katana/pull/877 is merged
we should either use `options.StoreFieldDir` or add back this comment

2024-11-29 12:02 UTC, dogancanbakir commented on cmd/katana/main.go
> +func handleError(message string, err error) {
Since this is going to fail, we should be more explicit about it. Something like `failWithError` or similar name would be great

2025-08-30 12:47 UTC, ehsandeep commented
closing due to inactivity.

2025-08-30 12:47 UTC, closed without merging